### PR TITLE
Add authorization service wrapper

### PR DESCRIPTION
**Pull request by esbullington**
This is a PR for the new authorization service.  The Authorization service is structures like the other services, but only has a single function that sits on its prototype: getToken

This function takes a options object with a required 'url' property, since sending the URL of the intended resource for the Authorization service is required (tokens carry permissions that are constrained by path).

The other possibility is instead of passing in the URL, we could pass in the service that the token will be used with, which "knows" what the URL is.  Would this be a better approach?

I'm open to suggestions on improvements, and will check back by in a few hours (I need to spend a block of time now finishing up additional TTS demo app features).

### CODE REVIEW

**Comment by esbullington** [comment]
Need to add test, one moment please.

**Comment by germanattanasio** [comment]
@esbullington I already fixed the test case that is failing so don't worry about that

**Comment by esbullington** [comment]
I can squash these if you'd like.

**Comment by germanattanasio** [comment]
Let me merge this first

**Comment by germanattanasio** [comment]
Can you add something in the readme to point out the new authorization service and how to use it ?

**Comment by esbullington** [comment]
Sure, I'll send another PR in a few hours with that info added to the README (after I finish TTS stuff).

**Pull request merged**
