### PR TITLE
Update STT and TTS examples and README

### PR DESCRIPTION
**Pull request by esbullington**
I'll also put in a PR for a fix to the TTS service here, there's still a '-beta' in the default link.

### CODE REVIEW

**Comment by esbullington** [comment]
Actually, I'll just put that fix here, it will be easier for you.  One moment, please.

**Comment by germanattanasio** [comment]
Eric we don't do that change until the service that was beta is removed.

**Comment by esbullington** [comment]
OK, but then the updated examples do not work.  Is that OK?

**Comment by germanattanasio** [comment]
For the examples we need to specify the url for now. then we will remove it

**Comment by esbullington** [comment]
I'm submitting a new one with those changes, with your new commits merged.

**Pull request closed without merging**
