### PR TITLE
adding Tone Analyzer v2

### PR DESCRIPTION
**Pull request by herchu**
Adds a new V2 api wrapper for Tone Analyzer. The Tone Analyzer API is changing (about to be published), mainly changing /synonym from POST to GET. 

v1 wrapper is unchanged. v2 wrapper is added. test cases for v2 are also added.

### CODE REVIEW

**Comment by germanattanasio** [comment]
Hey @herchu, I saw that you are sending `content-type: application/json` for `synonyms` and `scorecards`. If you set `json: true` it will automatically add the `content-type` header and parse the response as json, no need to add the header manually.  See [this](https://github.com/request/request#requestoptions-callback)

**Comment by herchu** [comment]
I just fixed the headers issue; using only the json:true property now

**Comment by herchu** [comment]
Detail of changes in V2:

changes
* synonym api is now GET and accepts a single word (and it is /synonyms, plural)
* synonym api now returns an object, not an array
* tone accepts a GET (alternative to POST)
* tone api now returns which words have synonyms available

other misc fixes
* improvements on synonyms dictionaries
* tone algorithms have also been improved
* fixed spelling to semantic_type in synonym response
* "hops" properties now make sense

**Comment by germanattanasio** [comment]
thanks @herchu

**Comment by nfriedly** [comment]
Published to npm in [v0.10.0](https://github.com/watson-developer-cloud/nodejs-wrapper/tree/v0.10.0)

**Pull request merged**
